name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libsoup2.4-dev javascriptcoregtk-4.0 libwebkit2gtk-4.0-dev libasound2-dev
    - name: Build
      run: cargo build --manifest-path src-tauri/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path src-tauri/Cargo.toml --verbose
